services:
  # ─────────────────────────────────────────────────────────────────────────────
  # Microfab : nœud Hyperledger Fabric tout-en-un
  # Utilisation des valeurs par défaut (Org1, channel1)
  # ─────────────────────────────────────────────────────────────────────────────
  microfab:
    image: ibmcom/ibp-microfab:latest
    container_name: microfab
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "2002:2002"
      - "2004:2004"
      - "2001:2001"
    volumes:
      - ./microfab-data:/opt/microfab/data
      - ./chaincode:/opt/microfab/chaincode
      - ./infra/docker_patches/index.cjs.js:/opt/microfab/chaincode/node_modules/@so-ric/colorspace/dist/index.cjs.js
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8080/ak/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s

  # ───────────────────────────────────────────────────────────────────────────
  # API Node.js : pont entre Laravel et Fabric
  # Adaptée à la config par défaut de Microfab (Org1 / channel1)
  # ───────────────────────────────────────────────────────────────────────────
  cacao-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: cacao-api
    restart: unless-stopped
    depends_on:
      microfab:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - MICROFAB_URL=http://microfab:8080
      - CHANNEL_NAME=channel1
      - CHAINCODE_NAME=cacao-contract
      - MSP_ID=Org1MSP
      - FABRIC_PEER_ENDPOINT=microfab:2004
      - PORT=3000
      - BLOCKCHAIN_API_KEY=mariuskym
    volumes:
      - ./chaincode:/app/chaincode:ro


  # explorerdb:
  #   image: hyperledger/explorer-db:latest
  #   container_name: explorerdb
  #   environment:
  #     - MYSQL_DATABASE=fabricexplorer
  #     - MYSQL_USER=hppoc
  #     - MYSQL_PASSWORD=password
  #     - MYSQL_ROOT_PASSWORD=password
  #   healthcheck:
  #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # explorer:
  #   image: hyperledger/explorer:latest
  #   container_name: explorer
  #   depends_on:
  #     explorerdb:
  #       condition: service_healthy
  #     microfab:
  #       condition: service_healthy
  #   ports:
  #     - "8090:8080"
  #   environment:
  #     - DATABASE_HOST=explorerdb
  #     - DATABASE_USERNAME=hppoc
  #     - DATABASE_PASSWD=password
  #     - DISCOVERY_AS_LOCALHOST=false
  #   volumes:
  #     - ./explorer-config/connection.json:/opt/explorer/app/platform/fabric/connection-profile/first-network.json
  #     - ./explorer-config/explorerconfig.json:/opt/explorer/app/explorerconfig.json
  #     - ./microfab-data/admin-org1:/tmp/crypto